Fixes loading of recipe content after clicking sidebar link
RyanNoelk/OpenEats pull request #102
Opened 2017-01-31 17:56 UTC by hermzz

No need to make a AJAX call from the ingredients and directions list, the content is already included in the initial recipe request.

As a bonus also improves the rating star code.

Fixes #101

2017-02-01 01:11 UTC, RyanNoelk requested changes

2017-02-01 01:11 UTC, RyanNoelk commented on frontend/modules/recipe/components/Ratings.js
> +    const stars = this.props.stars ? this.props.stars : 0;
Thanks for cleaning up the horrible hack of how I process Stars. But right now the user can enter a value > 5 for stars.

We need to make sure that 5 is the max and 0 is the min:

```
    if (stars > 5) {
      stars = 5
    } else if (stars < 0) {
      stars = 0
    }
```

2017-02-01 01:12 UTC, RyanNoelk commented on frontend/modules/recipe/components/Ratings.js
> +    const stars = this.props.stars ? this.props.stars : 0;
We can address the bigger problem or users entering large numbers in https://github.com/RyanNoelk/OpenEats/issues/79

2017-02-01 10:30 UTC, hermzz commented
Good point, I feel this needs to be addressed in the API as well.

2017-02-02 00:42 UTC, RyanNoelk approved these changes
LGTM, I'll let u merge it still this will have conflicts with your other PR. Pick one that is easier for you to resolve.

2017-02-02 09:43 UTC, merged