Adding default-superagent to set headers in all ajax calls we make
RyanNoelk/OpenEats pull request #145
Opened 2017-02-24 02:07 UTC by RyanNoelk

To Test: 
- make sure all the endpoints still work :)

2017-02-24 10:19 UTC, hermzz requested changes

2017-02-24 10:19 UTC, hermzz commented on frontend/modules/common/CustomSuperagent.js
> +var defaults = require('superagent-defaults');
Why not `import defaults from 'superagent-defaults'`? It looks kinda odd to mix up two different import styles.

2017-02-24 10:19 UTC, hermzz commented on frontend/modules/common/CustomSuperagent.js
> +export { request };
Similarly, why not just `export default request` or `module.exports = request`?

2017-02-25 04:06 UTC, RyanNoelk commented
I cleaned up the superagent common file. Let me know what you think :)

2017-02-25 10:42 UTC, hermzz approved these changes

2017-02-25 18:38 UTC, merged