Feature/contributing
RyanNoelk/OpenEats pull request #173
Opened 2017-03-24 03:45 UTC by RyanNoelk

https://github.com/RyanNoelk/OpenEats/issues/123

Let me know what you think.

2017-03-24 09:09 UTC, hermzz requested changes
Looks great!

2017-03-24 09:09 UTC, hermzz commented on README.md
> +OpenEats is a recipe management site that allows users to create, share, and store there personal collection of recipes. This fork uses Django Rest Framework as a backend and React (with flux) as a f
*their

2017-03-25 00:48 UTC, RyanNoelk commented
Fix the issue above and added a few corrects as well.

2017-03-25 15:36 UTC, hermzz approved these changes

2017-03-25 17:14 UTC, merged