Update Spanish translation
RyanNoelk/OpenEats pull request #259
Opened 2017-09-04 20:09 UTC by bglopez

Updated the Spanish translation for the new strings

2017-09-05 02:42 UTC, RyanNoelk requested changes
small nit, otherwise LGTM. Gracias!

2017-09-05 02:43 UTC, RyanNoelk commented on frontend/locale/es.json
> +  "nav.brand": "Open Eats",
This should be `OpenEats`

2017-09-05 10:16 UTC, DJCrashdummy requested changes
- a translation for line 87 is still missing: https://github.com/RyanNoelk/OpenEats/pull/254#discussion_r136487440
- it would be awesome if you can also address the minor issues mentioned in my comment https://github.com/RyanNoelk/OpenEats/issues/237#issuecomment-326549952

2017-09-05 10:16 UTC, DJCrashdummy commented on frontend/locale/es.json
> +  "footer.icon_credit": "Iconos diseñados por {link} ({ccLink})",
this reverts some changes from #257:
https://github.com/RyanNoelk/OpenEats/pull/257/files#diff-a60ed6296298c48b2bb1a5008fd05300
hopefully it is a correct translation...?

it should now be translated from: https://github.com/RyanNoelk/OpenEats/blob/f605cca61c049d30537b8909a91753563837d335/frontend/locale/en.json#L11

the reason and according "discussion":
https://github.com/RyanNoelk/OpenEats/pull/254/files/11781ba19e3180cfdb4db32a1520f88068f6f941#r136665863

2017-09-05 10:16 UTC, DJCrashdummy commented on frontend/locale/es.json
>    "ingredients.group_placeholder": "Group (leave blank for default)",
i guess you missed this one...

2017-09-05 15:22 UTC, DJCrashdummy commented
one last thing:
it would be very nice if you can take a look at line 37, if it still fits the latest minor changes at #260...
https://github.com/RyanNoelk/OpenEats/blob/5f13b447d451b068bcf7b3fef7f92aacefe805c0/frontend/locale/es.json#L37
https://github.com/RyanNoelk/OpenEats/blob/5f13b447d451b068bcf7b3fef7f92aacefe805c0/frontend/locale/en.json#L37

thank you very much @bglopez!!!

2017-09-12 01:03 UTC, RyanNoelk commented
Merging this now as I want to get it in. I will try and fix these issues in the core PR.

2017-09-12 01:04 UTC, merged