Use docker for development
RyanNoelk/OpenEats pull request #33
Opened 2016-11-30 22:33 UTC by hermzz

Creates two docker environments: `api` and `node`.
Setups up CORS and removes the proxy to the API through React.
With CORS we can make requests to other domains/ports.

2016-12-01 18:35 UTC, RyanNoelk requested changes
Thanks a ton for adding some much needed docker support! A few questions/comments: 

What are your thoughts on dockerizing the DB as well? I don't see a good reason for not doing it at this stage. 

I use OSX for development and I'm having some issues with the volume mounting for the frontend. I'm thinking that this is just a file watching issue, since the django server will auto update if I change a file. I'll take a closer look into it this weekend, if things are working for you.

Thanks!
-Ryan

2016-12-01 18:35 UTC, RyanNoelk commented on frontend/modules/common/config.js
> -  mini_browse: '/api/v1/recipe/mini-browse/?format=json',
This endpoint is needed. Its used to return a small (or large) random subset or recipes to be used on the home page and when viewing individual recipes.

2016-12-01 18:35 UTC, RyanNoelk commented on frontend/modules/common/config.js
> +var apiUrl = apiHost + '/api/v1'
semicolons ^^

2016-12-01 18:35 UTC, RyanNoelk commented on frontend/package.json
> +    "start:prod": "NODE_ENV=production webpack && node server.js",
This command shouldn't be called directly. 

running `NODE_ENV=production npm start` will call `start:prod` and run them with `NODE_ENV=production`

2016-12-01 18:55 UTC, hermzz commented
Dockerizing the DB should be fairly straight forward. I hadn't done it because the sqlite DB seemed to be fine, but I can give it a shot.

As for the volume issues, I seem to recall reading about people having trouble with it because of boot2docker. I think there was a quick fix that just required manually setting a `tick` setting. I'll try to find it.

2016-12-01 18:56 UTC, hermzz commented on frontend/modules/common/config.js
> -  mini_browse: '/api/v1/recipe/mini-browse/?format=json',
Added back, I think it got lost when I was merging changes.

2016-12-01 19:02 UTC, RyanNoelk commented
l'm mainly asking about the DB because I would like to use this for production soon as well. Downloading docker images is a lot more straight forward than building the code from source

2016-12-01 20:38 UTC, hermzz commented on frontend/webpack.config.js
> +    poll: 100,
@RyanNoelk Play around with these values. Apparently this is what fixes the refreshing issue on Mac.

2016-12-01 21:24 UTC, RyanNoelk commented
FYI, I did some quite digging and found a couple possible solutions to my mac problems. 

* docker-osx-dev - https://github.com/brikis98/docker-osx-dev
* Running docker natively - https://www.docker.com/products/overview - Looks like docker has a OSX beta.

2016-12-02 17:00 UTC, RyanNoelk commented
So the issue went away once I switched to native docker for mac. Having some cors related issues that I'll take a look at this weekend.

2016-12-02 17:00 UTC, RyanNoelk commented on frontend/webpack.config.js
> +    poll: 100,
Feel free to remove this. It's not needed anymore.

2016-12-03 19:45 UTC, RyanNoelk approved these changes

2016-12-03 19:45 UTC, RyanNoelk commented
LGTM!

2016-12-03 19:45 UTC, merged