Recipe editing
RyanNoelk/OpenEats pull request #45
Opened 2016-12-23 14:41 UTC by hermzz

Creating and editing recipes use the same form. It's been renamed `RecipeForm`
instead of `Create`.

2016-12-23 15:03 UTC, hermzz commented
It's a big one ;-). Mostly just renamed file though.

2016-12-23 15:10 UTC, RyanNoelk commented
This is awesome! I may or may not have time to really dig into this in the next day or so (visiting my girlfriends family for Christmas). I'll take a look as soon as possible.

2016-12-25 11:55 UTC, RyanNoelk requested changes
Doing a quick look over of the style and functionality this looks good.

2016-12-25 11:55 UTC, RyanNoelk commented on frontend/modules/recipe_form/components/DirectionList.js
> +          <button onClick={ this.props.deleteInstruction }>
You should add some color/style to this button. Something like: `className="btn btn-danger"`. You could even consider using the [glyph-icons](http://getbootstrap.com/components/#glyphicons-glyphs) that bootstrap provides.

2016-12-25 11:55 UTC, RyanNoelk commented on frontend/modules/recipe_form/components/IngredientList.js
> +          <button onClick={ this.props.deleteIngredient }>
You should add some color/style to this button. (See comment above)

2016-12-25 11:58 UTC, RyanNoelk commented
I have one question: how users will navigate here? There should be a button on the recipe page that a user can click to edit a recipe.

There would also need to be permissions that only allow certain users to access and edit recipes. I believe the backend has these auth checks already but the frontend would need them as well. This also just might be out of scope for this PR. I think we should just get the the editing piece working. Then move on to making sure users can't get where they are not allowed on the frontend.

2016-12-27 14:57 UTC, hermzz commented
Good call on the buttons, although I think there may be a better way to display the two lists, and specifically the ingredients one. The delete button needs the label or it'll look awkwardly aligned so maybe the solution is to remove the labels for the other fields? We already include the names on blank ones and it's easy to figure out what each field is when the values are entered.

Regarding the user journey, I hadn't included it in the PR because I still haven't figured out how to do it properly and it felt like it'd be better off as a future PR. Ideally we'd include a link on each recipe page but only when the owner views them. Including a check to make sure the logged in user matches the recipe owner when going directly to the URL should be easy enough.

2016-12-27 15:35 UTC, RyanNoelk commented
I agree with removing the labels on the ingredients fields. They really don't need them and it just adds to the length of the page. Feel free to drop them.

As for the user journey, I'll create an issue for it. If you want to take that up next feel free. Your comment above is exactly what I would be looking for as well.

2016-12-27 15:38 UTC, RyanNoelk requested changes

2016-12-27 15:38 UTC, RyanNoelk commented on frontend/modules/recipe_form/components/DirectionList.js
> +      step: instructions[instructions.length - 1].step + 1,
I did find one other issue, `instructions.length` is zero when creating a new recipe. We'll need a check here to deal with the case if no instructions exist.

2016-12-27 17:00 UTC, hermzz commented on frontend/modules/recipe_form/components/DirectionList.js
> +      step: instructions[instructions.length - 1].step + 1,
Good catch, fixed. Figured I might also add some checks to not allow users to submit recipes with empty instructions, but then I realised there's no frontend validation at all so I'll create a separate issue for it.

2016-12-28 00:07 UTC, RyanNoelk requested changes
Found a few more things. Though I think this is the last of the issues. :)

2016-12-28 00:07 UTC, RyanNoelk commented on frontend/modules/recipe_form/components/RecipeForm.js
> +    console.log('update', name, value.map((i,k) => { return i.title;}).join(','));
remove console.log

2016-12-28 00:07 UTC, RyanNoelk commented on frontend/modules/recipe_form/actions/RecipeActions.js
> +      delete data['photo'];
Lets make this the same as the edit sections and add a TODO to merge these two at some point, since the only line that is different is put vs post.

```
    let photo = false;
    if (data.photo){
       photo = data.photo;
    }

    delete data['photo'];
    delete data['photo_thumbnail'];
```

2017-01-08 18:04 UTC, RyanNoelk approved these changes

2017-01-08 18:04 UTC, merged