Recipe navigation
RyanNoelk/OpenEats pull request #63
Opened 2017-01-15 23:09 UTC by hermzz

Shows user an edit recipe link when they're looking at they're own recipes.
Redirects users who don't own the recipe away from the edit recipe page.

2017-01-16 20:22 UTC, RyanNoelk requested changes
A few comments. Looks great though :)

2017-01-16 20:22 UTC, RyanNoelk commented on frontend/modules/recipe/components/Recipe.js
> +                  <div>{ formatMessage(messages.created_by) }: { this.props.data.username } { this.showEditLink() }</div>
This isn't the best place to put the button since the user who created the recipe will only show if there is no source provided.  It would be better if this lived outside of this div:

``` javascript
<div className="col-lg-6 col-xs-12">
	{ (this.props.data.source) ?
	    <div>{ formatMessage(messages.source) }: { this.props.data.source }</div>
	    :
	    <div>{ formatMessage(messages.created_by) }: { this.props.data.username }</div>
	} 
	{ this.showEditLink() }
</div>
```

2017-01-16 20:22 UTC, RyanNoelk commented on frontend/modules/recipe/components/Recipe.js
> +    if (this.props.user.id === this.props.data.author) {
If a user is not logged in, `user` will be null. Trying to access a property of a null value (`id` in this case) breaks bundle. We should check to make sure that user is not null before proceeding. Something like this:

``` javascript
    if (this.props.user !== null) {
      if (this.props.user.id === this.props.data.author) {
        return (
          <Link to={ "/recipe/edit/" + this.props.data.id }>
            <button className="btn btn-primary btn-sm">Edit recipe</button>
          </Link>
        )
      }
    }
```

2017-01-16 20:25 UTC, hermzz commented on frontend/modules/recipe/components/Recipe.js
> +                  <div>{ formatMessage(messages.created_by) }: { this.props.data.username } { this.showEditLink() }</div>
Ah, I totally misunderstood what source was then. On a related note, why show the source instead of the user? Wouldn't you want to show both anyway?

2017-01-16 20:35 UTC, RyanNoelk commented on frontend/modules/recipe/components/Recipe.js
> +                  <div>{ formatMessage(messages.created_by) }: { this.props.data.username } { this.showEditLink() }</div>
When I added the source field, I wanted it as a way of tracking a recipe that was copied from some other site. The only reason that I didn't show both was I couldn't find a way to make it look nice. Feel free to play around with the styles if you wanna display both of them.

2017-01-16 21:35 UTC, hermzz commented
Moved stuff around a bit: 
* Now the source is a link but the text is only the domain rather than the full URL.
* The `created by` shows on a new line underneath it.
* The `last updated` shows on a new line underneath it, but is hidden on `md` and lower.
* The edit button is aligned all the way right.

2017-01-17 01:32 UTC, RyanNoelk commented on frontend/modules/recipe_form/components/RecipeForm.js
> +        browserHistory.push('/');
A few things here:

1. Line 60 needs a semi-colon.
2. Line 61 is having the same user check issue. `user` is null.
3. Doing a push here breaks the browse history. If a user tries to go to the edit page, then hits the back button, its a never ending loop.

IMHO, when a user tries to go to the edit page without permission it should redirect them to the recipe view page. While also keeping the browser history intact.

2017-01-17 20:21 UTC, hermzz commented on frontend/modules/recipe_form/components/RecipeForm.js
> +        browserHistory.push('/');
The second point brings up the issue #65, we should be doing basic auth checks before the user even hits that path.

2017-01-17 21:45 UTC, RyanNoelk approved these changes
LGTM

2017-01-17 21:47 UTC, merged