Shows default image in the frontend
RyanNoelk/OpenEats pull request #91
Opened 2017-01-26 22:04 UTC by hermzz

Because finding a new logo image is outside of the scope of this PR I've just created a placeholder for the time being.

Fixes #82.

2017-01-27 04:46 UTC, RyanNoelk requested changes
We should also drop the default image: `api/base/default.png` and the management command folder: `api/base/management`. We are not using them anymore

2017-01-27 04:46 UTC, RyanNoelk commented on frontend/modules/recipe/components/Recipe.js
> +        <img className="img-responsive" src={ this.props.data.photo_thumbnail } />
I think we should also show the default image here as well. Just doesn't look as good without it, IMO.

2017-01-27 04:48 UTC, RyanNoelk commented on frontend/modules/recipe/components/Recipe.js
>          <h1 className="title hidden-xs">{this.props.data.title}</h1>
Should we only show this header if there is an Image? Looks weird to have it twice so quickly. Thoughts?

2017-01-27 15:22 UTC, hermzz commented on frontend/modules/recipe/components/Recipe.js
>          <h1 className="title hidden-xs">{this.props.data.title}</h1>
Good point, but now that I've had a good look, I'm not convinced the current layout makes a lot of sense. If the image exists, we show the image twice, which looks kinda weird. And if there is no image, then we show the title of the recipe in a different place and a useless placeholder. I feel like we should either just show the large image first and no first header or thumbnail. Or just the thumbnail (with a placeholder if no image) and have the green title always be the header. Or maybe the large image appears under the green title? 

I'm going to remove the first title if the image doesn't exist for the time being, and we can open a separate issue to see if we can improve this page.

2017-01-27 16:26 UTC, RyanNoelk reviewed
I'm still seeing the default image in the api `api/base/default.png`. I'm not 100% sure of the license for that, we should drop it.

Otherwise LGTM!

2017-01-27 16:27 UTC, RyanNoelk commented on frontend/modules/recipe/components/Recipe.js
>          <h1 className="title hidden-xs">{this.props.data.title}</h1>
I'm by no means a UX/UI expert. If you have some ideas, I'd love to see them

2017-01-30 13:50 UTC, hermzz commented
Good point, deleted!

2017-01-30 15:27 UTC, RyanNoelk commented
Maybe I'm crazy but I'm not seeing the image as deleted. Did you forget to push a commit?

2017-01-30 15:29 UTC, hermzz commented
Not crazy, I'm a moron. Commit pushed for reals this time.

2017-01-30 17:58 UTC, RyanNoelk approved these changes

2017-01-30 17:58 UTC, merged